name: hi
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        uses: ./
        with:
          node-version: ${{ matrix.node-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: npm start
